plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/github",
     { "assets": [{ "path": "charmap", "label": "charmap (linux/amd64)" }] }]
