name: Release Charmap

on:
  push:
    branches: [main]          # every commit ships
  workflow_dispatch:          # manual trigger
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/charmap
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # tag + release
      packages: write         # docker push
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - uses: actions/setup-go@v5
      with: { go-version: "1.24", cache: true }
    - name: Run unit tests
      run: go test ./...
    - name: semantic-release
      id: semrel
      uses: cycjimmy/semantic-release-action@v4
      with:
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        npm_config_loglevel: error
    # - name: Build charmap
    #   if: steps.semrel.outputs.new_release_published == 'true'
    #   run: |
    #     CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    #     go build -trimpath -ldflags="-s -w" -o charmap .
    - uses: docker/setup-qemu-action@v3
      if: steps.semrel.outputs.new_release_published == 'true'
    - uses: docker/setup-buildx-action@v3
      if: steps.semrel.outputs.new_release_published == 'true'
    - uses: docker/login-action@v3
      if: steps.semrel.outputs.new_release_published == 'true'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & push Docker image
      if: steps.semrel.outputs.new_release_published == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.semrel.outputs.release_version }}
          ${{ env.IMAGE_NAME }}:latest
